

export const TEST_ACTION = 'TEST_ACTION'
// LOADING ACTION
export const LOADING_REQUEST = 'LOADING_REQUEST'
export const LOADING = 'LOADING'
export const UNLOADING = 'UNLOADING'

// LOGIN ACTION
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'
export const LOGOUT = 'LOGOUT'
export const GET_TOKEN = 'GET_TOKEN'
export const FETCH_USER = 'FETCH_USER'
export const GET_USER = 'GET_USER'
// VOCA COURSE
export const GET_ALL_VOCA_SUCCESS = 'GET_ALL_VOCA_SUCCESS'
export const GET_ALL_VOCA_FAILURE = 'GET_ALL_VOCA_FAILURE'
export const GET_VOCA_SUCCESS = 'GET_VOCA_SUCCESS'
export const GET_VOCA_FAILURE = 'GET_VOCA_FAILURE'
// VOCA/ TOPIC 
export const GET_TOPIC_SUCCESS = 'GET_TOPIC_SUCCESS'
export const GET_TOPIC_FAILURE = 'GET_TOPIC_FAILURE'
export const UPDATE_TOPIC_SUCCESS = 'UPDATE_TOPIC_SUCCESS'

// PRACTICE LISTEN ACTION
export const FETCH_PRACTICE_LISTEN_REQUEST = 'FETCH_PRACTICE_LISTEN_REQUEST'
export const FETCH_PRACTICE_LISTEN_SUCCESS = 'FETCH_PRACTICE_LISTEN_SUCCESS'
export const FETCH_PRACTICE_LISTEN_FAILURE = 'FETCH_PRACTICE_LISTEN_FAILURE'


//LISTEN COURSE
export const FETCH_LISTEN_COURSE_REQUEST = 'FETCH_LISTEN_COURSE_REQUEST'
export const FETCH_LISTEN_COURSE_SUCCESS = 'FETCH_LISTEN_COURSE_SUCCESS'
export const FETCH_LISTEN_COURSE_FAILURE = 'FETCH_LISTEN_COURSE_FAILURE'

//LISTEN PART
export const FETCH_LISTEN_PART_REQUEST = 'FETCH_LISTEN_PART_REQUEST'
export const FETCH_LISTEN_PART_SUCCESS = 'FETCH_LISTEN_PART_SUCCESS'
export const FETCH_LISTEN_PART_FAILURE = 'FETCH_LISTEN_PART_FAILURE'

