// 
export const SET_SPEAK_SUCCESS = 'SET_SPEAK_SUCCESS'
export const SET_SPEAK_SLOW_SUCCESS = 'SET_SPEAK_SLOW_SUCCESS'
// POP UP
export const TURN_ON_POPUP_LOGIN = 'TURN_ON_POPUP_LOGIN'
export const TURN_OFF_POPUP_LOGIN = 'TURN_OFF_POPUP_LOGIN'

// 
export const TEST_ACTION = 'TEST_ACTION'
// LOADING ACTION
export const ONLOADING = 'ONLOADING'
export const UNLOADING_REQUEST = 'UNLOADING_REQUEST'
export const UNLOADING_SUCCESS = 'UNLOADING_SUCCESS'

// LOGIN ACTION
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'
export const LOGOUT = 'LOGOUT'
export const GET_TOKEN = 'GET_TOKEN'
export const FETCH_USER = 'FETCH_USER'
export const GET_USER = 'GET_USER'
// VOCA COURSE
export const GET_ALL_VOCA_SUCCESS = 'GET_ALL_VOCA_SUCCESS'
export const GET_ALL_VOCA_FAILURE = 'GET_ALL_VOCA_FAILURE'
export const GET_VOCA_SUCCESS = 'GET_VOCA_SUCCESS'
export const GET_VOCA_FAILURE = 'GET_VOCA_FAILURE'
// VOCA/ TOPIC 
export const GET_TOPIC_SUCCESS = 'GET_TOPIC_SUCCESS'
export const GET_TOPIC_FAILURE = 'GET_TOPIC_FAILURE'
export const UPDATE_TOPIC_SUCCESS = 'UPDATE_TOPIC_SUCCESS'

// PRACTICE LISTEN ACTION
export const FETCH_PRACTICE_LISTEN_REQUEST = 'FETCH_PRACTICE_LISTEN_REQUEST'
export const FETCH_PRACTICE_LISTEN_SUCCESS = 'FETCH_PRACTICE_LISTEN_SUCCESS'
export const FETCH_PRACTICE_LISTEN_FAILURE = 'FETCH_PRACTICE_LISTEN_FAILURE'


//LISTEN COURSE
export const FETCH_LISTEN_COURSE_REQUEST = 'FETCH_LISTEN_COURSE_REQUEST'
export const FETCH_LISTEN_COURSE_SUCCESS = 'FETCH_LISTEN_COURSE_SUCCESS'
export const FETCH_LISTEN_COURSE_FAILURE = 'FETCH_LISTEN_COURSE_FAILURE'

//LISTEN PART
export const FETCH_LISTEN_PART_REQUEST = 'FETCH_LISTEN_PART_REQUEST'
export const FETCH_LISTEN_PART_SUCCESS = 'FETCH_LISTEN_PART_SUCCESS'
export const FETCH_LISTEN_PART_FAILURE = 'FETCH_LISTEN_PART_FAILURE'


export const GET_USER_VOCA_PROCESS = 'GET_USER_VOCA_PROCESS_SUCCESS'

export const SET_QUESTION_PLAYING = 'SET_QUESTION_PLAYING'
export const SET_QUESTION_TRUE = 'SET_QUESTION_TRUE'

// ALL TOPIC GRAMMAR ACTION
export const FETCH_GRAMMAR_REQUEST = 'FETCH_GRAMMAR_REQUEST'
export const FETCH_GRAMMAR_SUCCESS = 'FETCH_GRAMMAR_SUCCESS'
export const FETCH_GRAMMAR_FAILURE = 'FETCH_GRAMMAR_FAILURE'

// ONE TOPIC GRAMMAR ACTION
export const FIND_TOPIC_GRAMMAR_REQUEST = 'FIND_TOPIC_GRAMMAR_REQUEST'
export const FIND_TOPIC_GRAMMAR_SUCCESS = 'FIND_TOPIC_GRAMMAR_SUCCESS'
export const FIND_TOPIC_GRAMMAR_FAILURE = 'FIND_TOPIC_GRAMMAR_FAILURE'

// STORE WORD BY ID USER ACTION
export const FIND_STORE_WORD_REQUEST = 'FIND_STORE_WORD_REQUEST'
export const FIND_STORE_WORD_SUCCESS = 'FIND_STORE_WORD_SUCCESS'
export const FIND_STORE_WORD_FAILURE = 'FIND_STORE_WORD_FAILURE'

//TOKEN
export const RESET_TOKEN = 'RESET_TOKEN'

// FETCH NOTE ACTION
export const FETCH_NOTE_REQUEST = 'FETCH_NOTE_REQUEST'
export const FETCH_NOTE_SUCCESS = 'FETCH_NOTE_SUCCESS'
export const FETCH_NOTE_FAILURE = 'FETCH_NOTE_FAILURE'

// ADD NOTE ACTION
export const ADD_NOTE_REQUEST = 'ADD_NOTE_REQUEST'
export const ADD_NOTE_SUCCESS = 'ADD_NOTE_SUCCESS'
export const ADD_NOTE_FAILURE = 'ADD_NOTE_FAILURE'

// UPDATE NOTE ACTION
export const UPDATE_NOTE_REQUEST = 'UPDATE_NOTE_REQUEST'
export const UPDATE_NOTE_SUCCESS = 'UPDATE_NOTE_SUCCESS'
export const UPDATE_NOTE_FAILURE = 'UPDATE_NOTE_FAILURE'

// REMOVE NOTE ACTION
export const REMOVE_NOTE_REQUEST = 'REMOVE_NOTE_REQUEST'
export const REMOVE_NOTE_SUCCESS = 'REMOVE_NOTE_SUCCESS'
export const REMOVE_NOTE_FAILURE = 'REMOVE_NOTE_FAILURE'

// STORE QUESTION BY ID USER ACTION
export const FIND_STORE_QUESTION_REQUEST = 'FIND_STORE_QUESTION_REQUEST'
export const FIND_STORE_QUESTION_SUCCESS = 'FIND_STORE_QUESTION_SUCCESS'
export const FIND_STORE_QUESTION_FAILURE = 'FIND_STORE_QUESTION_FAILURE'

// FETCH SPEAK LESSON ACTION
export const FETCH_SPEAK_LESSON_REQUEST = 'FETCH_SPEAK_LESSON_REQUEST'
export const FETCH_SPEAK_LESSON_SUCCESS = 'FETCH_SPEAK_LESSON_SUCCESS'
export const FETCH_SPEAK_LESSON_FAILURE = 'FETCH_SPEAK_LESSON_FAILURE'

// FIND SPEAK QUESTION ACTION
export const FIND_SPEAK_QUESTION_REQUEST = 'FIND_SPEAK_QUESTION_REQUEST'
export const FIND_SPEAK_QUESTION_SUCCESS = 'FIND_SPEAK_QUESTION_SUCCESS'
export const FIND_SPEAK_QUESTION_FAILURE = 'FIND_SPEAK_QUESTION_FAILURE'

// FETCH SPEAK GRAMMAR ACTION
export const FETCH_SPEAK_GRAMMAR_REQUEST = 'FETCH_SPEAK_GRAMMAR_REQUEST'
export const FETCH_SPEAK_GRAMMAR_SUCCESS = 'FETCH_SPEAK_GRAMMAR_SUCCESS'
export const FETCH_SPEAK_GRAMMAR_FAILURE = 'FETCH_SPEAK_GRAMMAR_FAILURE'

// FIND SPEAK GRAMMAR BY ID ACTION
export const FIND_SPEAK_GRAMMAR_REQUEST = 'FIND_SPEAK_GRAMMAR_REQUEST'
export const FIND_SPEAK_GRAMMAR_SUCCESS = 'FIND_SPEAK_GRAMMAR_SUCCESS'
export const FIND_SPEAK_GRAMMAR_FAILURE = 'FIND_SPEAK_GRAMMAR_FAILURE'

// FETCH WRITE LESSON ACTION
export const FETCH_WRITE_LESSON_REQUEST = 'FETCH_WRITE_LESSON_REQUEST'
export const FETCH_WRITE_LESSON_SUCCESS = 'FETCH_WRITE_LESSON_SUCCESS'
export const FETCH_WRITE_LESSON_FAILURE = 'FETCH_WRITE_LESSON_FAILURE'

// FIND WRITE QUESTION ACTION
export const FIND_WRITE_QUESTION_REQUEST = 'FIND_WRITE_QUESTION_REQUEST'
export const FIND_WRITE_QUESTION_SUCCESS = 'FIND_WRITE_QUESTION_SUCCESS'
export const FIND_WRITE_QUESTION_FAILURE = 'FIND_WRITE_QUESTION_FAILURE'

// FETCH WRITE GRAMMAR ACTION
export const FETCH_WRITE_GRAMMAR_REQUEST = 'FETCH_WRITE_GRAMMAR_REQUEST'
export const FETCH_WRITE_GRAMMAR_SUCCESS = 'FETCH_WRITE_GRAMMAR_SUCCESS'
export const FETCH_WRITE_GRAMMAR_FAILURE = 'FETCH_WRITE_GRAMMAR_FAILURE'

// FIND WRITE GRAMMAR ACTION
export const FIND_WRITE_GRAMMAR_REQUEST = 'FIND_WRITE_GRAMMAR_REQUEST'
export const FIND_WRITE_GRAMMAR_SUCCESS = 'FIND_WRITE_GRAMMAR_SUCCESS'
export const FIND_WRITE_GRAMMAR_FAILURE = 'FIND_WRITE_GRAMMAR_FAILURE'