

export const TEST_ACTION = 'TEST_ACTION'

// LOGIN ACTION
export const LOGIN = 'LOGIN'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'
export const LOGOUT = 'LOGOUT'

// COURSE ACTION
export const FETCH_COURSE_REQUEST = 'FETCH_COURSE_REQUEST'
export const FETCH_COURSE_SUCCESS = 'FETCH_COURSE_SUCCESS'
export const FETCH_COURSE_FAILURE = 'FETCH_COURSE_FAILURE'
export const CREATE_COURSE_REQUEST = 'CREATE_COURSE_REQUEST'
export const CREATE_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS'
export const CREATE_COURSE_FAILURE = 'CREATE_COURSE_FAILURE'

// PRACTICE LISTEN ACTION
export const FETCH_PRACTICE_LISTEN_REQUEST = 'FETCH_PRACTICE_LISTEN_REQUEST'
export const FETCH_PRACTICE_LISTEN_SUCCESS = 'FETCH_PRACTICE_LISTEN_SUCCESS'
export const FETCH_PRACTICE_LISTEN_FAILURE = 'FETCH_PRACTICE_LISTEN_FAILURE'

//LISTEN COURSE
export const FETCH_LISTEN_COURSE_REQUEST = 'FETCH_LISTEN_COURSE_REQUEST'
export const FETCH_LISTEN_COURSE_SUCCESS = 'FETCH_LISTEN_COURSE_SUCCESS'
export const FETCH_LISTEN_COURSE_FAILURE = 'FETCH_LISTEN_COURSE_FAILURE'